# Generated by Django 4.0.3 on 2022-04-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_type',
            old_name='type',
            new_name='client_type_id',
        ),
    ]
