# Generated by Django 4.0.3 on 2022-04-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_type', '0002_rename_type_client_type_client_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_type',
            old_name='client_type_id',
            new_name='driver',
        ),
    ]
