# Generated by Django 4.0.3 on 2022-04-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_type', '0003_rename_client_type_id_client_type_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_type',
            old_name='driver',
            new_name='type',
        ),
    ]
