# Generated by Django 3.2.8 on 2022-04-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_type', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_type.client_type')),
            ],
        ),
    ]
