# Generated by Django 3.2.8 on 2022-04-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='account_balance',
        ),
    ]
