# Generated by Django 4.0.3 on 2022-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
