# Generated by Django 4.0.3 on 2022-04-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_password_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
