# Generated by Django 4.0.3 on 2022-04-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_id',
        ),
    ]
