# Generated by Django 4.0.3 on 2022-04-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_type',
            new_name='client_type_id',
        ),
    ]
