# Generated by Django 4.0.3 on 2022-04-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_rename_client_type_client_client_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_type_id',
            new_name='type',
        ),
    ]
