# Generated by Django 4.0.3 on 2022-04-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_rename_client_type_id_client_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
    ]
