# Generated by Django 4.0.3 on 2022-04-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('pickuplat', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('pickuplng', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('dropofflat', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('dropofflng', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='clients.client')),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_id', to='clients.client')),
            ],
        ),
    ]
