# Generated by Django 4.0.3 on 2022-04-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(db_column='driver_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_id', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='clients.client'),
        ),
    ]
