# Generated by Django 4.0.3 on 2022-04-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_driver_alter_trip_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
