# Generated by Django 4.0.3 on 2022-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_accepted_trip_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
