# Generated by Django 4.0.3 on 2022-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_lat_trip_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='lat',
            new_name='droppofflat',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='lng',
            new_name='droppofflng',
        ),
        migrations.AddField(
            model_name='trip',
            name='pickuplat',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickuplng',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
