# Generated by Django 4.0.3 on 2022-04-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_rename_lat_trip_droppofflat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='droppofflat',
            new_name='dropofflat',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='droppofflng',
            new_name='dropofflng',
        ),
    ]
