# Generated by Django 4.0.3 on 2022-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_droppofflat_trip_dropofflat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dropofflat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropofflng',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickuplat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickuplng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
