# Generated by Django 4.0.3 on 2022-04-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_dropofflat_alter_trip_dropofflng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dropofflat',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropofflng',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickuplat',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickuplng',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
